[#24] Prepare for announcement
union-platform/website pull request #29
Opened 2022-11-28 20:30 UTC by rexolion

## Related issue(s)

Resolves:

## :white_check_mark: Checklist for your Pull Request

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from silently reappearing again.

- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
  - [ ] I checked whether I should update/add links to the figma UI-kit and did so if necessary:
    - [FIGMA UI-KIT](https://www.figma.com/file/2St3zSul4fHnLffqy3WK7P/%5B-union-%5D-mobile?node-id=4687%3A34299)

- Public contracts
  - [ ] My changes doesn't break any Licenses.
  - [ ] I added an entry to the [changelog](../tree/master/CHANGES.md) if my changes are visible to the users
        and
  - [ ] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [ ] My commits comply with [the policy used in Union](https://github.com/union-platform/guides/blob/master/commits.md).
- [ ] My code complies with the [styles guide](https://github.com/union-platform/guides/blob/master/README.md#programming-languages).

#### Before merging (mandatory)
- [ ] Check for `fixup!` or `squash!` commits in this branch
- [ ] Check __target__  branch of PR is set correctly

2022-11-28 20:31 UTC, rexolion reviewed
![](https://img.shields.io/badge/Accessibility-98-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-92-green?style=flat-square) ![](https://img.shields.io/badge/Performance-49-red?style=flat-square) ![](https://img.shields.io/badge/Progressive%20Web%20App-90-green?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | https://www.unionapp.cc |

Not what you expected? Are your scores flaky? **GitHub runners could be the cause.**
[Try running on Foo instead](https://www.foo.software/docs/lighthouse-check-github-action/examples#running-on-foo-and-saving-results)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["mobile:https://www.unionapp.cc"]COMMENT_ID -->

2022-11-29 08:53 UTC, worm2fed requested changes

2022-11-29 08:53 UTC, worm2fed commented on src/_data/footer.json
> +      "link": "https://t.me/unionapp_cc_dev",
sorry, I've changed chat link

https://t.me/unionapp_cc_discussions

2022-11-29 08:53 UTC, worm2fed commented on src/_data/nav.json
> +  "navBtnLink": "https://t.me/unionapp_cc_dev",
sorry, I've changed chat link

https://t.me/unionapp_cc_discussions

2022-11-29 08:53 UTC, worm2fed commented on src/index.md
> +    link: "https://t.me/unionapp_cc_dev"
sorry, I've changed chat link

https://t.me/unionapp_cc_discussions

2022-11-29 09:08 UTC, worm2fed commented
@rexolion maybe we can have single source for same links across all files?

2022-11-30 12:51 UTC, rexolion commented
> @rexolion maybe we can have single source for same links across all files?

Great idea, but I think for now it's ok. When the website would become bigger, it will be more sense in it.

2022-11-30 12:54 UTC, worm2fed commented
good!

>  Fix white vertical lines in animation
are you going to fix it? or postpone?

2022-12-12 12:14 UTC, rexolion commented
> good!
> 
> > Fix white vertical lines in animation
> 
> are you going to fix it? or postpone?

Yeah, fuck it. It's easier to remove it or ignore it than fix it — weird behavior of SVG animations.

2022-12-12 12:17 UTC, worm2fed commented
@rexolion in chrome it's fine, but not in safari

did you saw this? https://stackoverflow.com/questions/37726195/why-does-my-css-animation-not-work-in-safari

pls try; if it will not work - lets proceed without it

2023-04-08 09:22 UTC, worm2fed requested changes

2023-04-08 09:22 UTC, worm2fed commented on src/_data/footer.json
> +      "link": "https://t.me/unionapp_cc_discussions",
https://t.me/unionapp_cc

2023-04-08 09:22 UTC, worm2fed commented on src/_data/footer.json
> +      "text": "Telegram Chat"
Telegram

2023-04-08 09:22 UTC, worm2fed commented on src/_data/footer.json
> +      "text": "Telegram Channel"
Telegram

2023-04-08 09:22 UTC, worm2fed commented on src/_data/nav.json
>  }
Missing newline at the end of file

2023-04-08 09:22 UTC, worm2fed commented on src/_includes/layouts/features.njk
>  {% endblock %}
Missing newline at the end of file

2023-04-08 09:22 UTC, worm2fed commented on src/_includes/layouts/homepage.njk
>  {% endblock %}
Missing newline at the end of file

2023-04-08 09:22 UTC, worm2fed commented on src/features/activities.md
> +The user may cycle among all modes (date/time, timer, mystery answer) by pressing the mode button.
Missing newline at the end of file

2023-04-08 09:22 UTC, worm2fed commented on src/features/people.md
> +The user may cycle among all modes (date/time, timer, mystery answer) by pressing the mode button.
Missing newline at the end of file

2023-04-08 10:34 UTC, rexolion commented on src/_data/nav.json
>  }
We don't put a newline on EOF in JSON format. It's a data format.

2023-04-08 10:43 UTC, rexolion commented on src/_data/nav.json
>  }
But fuck it, I made it :)

2023-04-08 11:09 UTC, worm2fed commented on src/_data/nav.json
>  }
It can be treated as config as well. Any way it's source file as for me)

Thank you))

2023-04-08 11:12 UTC, worm2fed commented on .gitignore
> +.pnp.loader.mjs
And newline here as well))

2023-04-08 11:18 UTC, rexolion commented
@worm2fed  Do you want Telegram links to be this way?:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/20303265/230718286-20afd5ae-69e4-4280-b9b1-d205034c164b.png">

Or every link in contacts?

2023-04-08 11:20 UTC, worm2fed commented
@rexolion lets hide titles in footer for now) and I think telegram channel is enough (without chat)

2023-04-08 20:48 UTC, worm2fed approved these changes

2023-04-10 05:35 UTC, merged